; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = noisy_display_home

[env]
; genuinely universal settings go here

[esp_base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200	
build_flags = 
	-DBOARD_HAS_PSRAM

[usb_native]
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

;
; Boards
[board_n16r8]
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

[board_n32r16]
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 32MB
; board_build.partitions = default_32MB.csv
; board_build.arduino.memory_type = qio_opi
; board_build.flash_mode = qio
; board_build.psram_type = opi
; board_upload.flash_size = 16MB
; board_upload.maximum_size = 16777216
; board_build.partitions = default_16MB.csv

;
; Networks
;
[wifi_home]
build_flags =
	${esp_base.build_flags}
    -DWIFI_NETWORK_HOME

[wifi_phone]
build_flags =
	${esp_base.build_flags}
    -DWIFI_NETWORK_PHONE

[wifi_wokwi]
build_flags =
	${esp_base.build_flags}
    -DWIFI_NETWORK_WOKWI

;
; Programs
;
[noisy_display]	
lib_deps = 
	adafruit/Adafruit NeoPixel
	adafruit/Adafruit SH110X
build_src_filter = 
	+<*>
	-<experiments/>

[web_server]
lib_deps = 
    bblanchon/ArduinoJson	
build_src_filter = 
	-<*>
	+<heartbeat.cpp>
	+<experiments/web_server.cpp>

[esp_test]
build_src_filter = 
	-<*>
	+<experiments/board_test.cpp>

[modem_port]
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101

[serial_port]
upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110

;
; Executables
;
[env:web_server_home]
extends = 
	esp_base
	usb_native
	board_n16r8
	web_server
	wifi_home

[env:noisy_display_home]
extends = 
	esp_base
	board_n16r8
	noisy_display
	wifi_home
	usb_native
	modem_port

[env:board_test]
extends = 
	esp_base
	board_n32r16
	esp_test
	serial_port

[env:native]
build_type = test
platform = native
test_framework = unity
build_flags =
    -std=c++17




; [env:esp32]
; extends = esp_base
; build_src_filter = 
; 	+<*>
; 	-<experiments/>

; [env:wifi-test]
; extends = esp_base
; build_src_filter = 
; 	-<*>
; 	+<heartbeat.cpp>
; 	+<experiments/wifi_events.cpp>

; [env:wifi-scan]
; extends = esp_base
; build_src_filter = 
; 	-<*>
; 	+<experiments/wifi_scanner.cpp>

; ; source files are temporary for ease of use
; [env:wifi_base]
; extends = esp_base
; build_src_filter = 
; 	-<*>
; 	+<heartbeat.cpp>
; 	+<experiments/web_server.cpp>


; [env:wifi-home]
; extends = env:wifi_base
; build_flags =
;     -DWIFI_NETWORK_HOME

; [env:wifi-phone]
; extends = env:wifi_base
; build_flags =
;     -DWIFI_NETWORK_PHONE

; [env:wifi-wokwi]
; extends = env:wifi_base
; build_flags =
;     -DWIFI_NETWORK_WOKWI

; [env:webserver-test]
; extends = env:wifi-home
; ; build_flags =
; ;     -DWIFI_NETWORK_HOME

; [env:webserver-wokwi]
; extends = env:wifi-wokwi
; build_flags =
;     -DWIFI_NETWORK_WOKWI
; ; build_src_filter = 
; ; 	-<*>
; ; 	+<heartbeat.cpp>
; ; 	+<experiments/web_server.cpp>

; ; [env:wifi-wokwi]
; ; build_src_filter = 
; ; 	-<*>
; ; 	+<experiments/neopixel_hysteresis.cpp>
