; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = noisy_display

[env]
; genuinely universal settings go here

[esp_base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200	
base_flags = 
	-DBOARD_HAS_PSRAM

[usb_native]
usb_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

;
; Boards, named after birds
; "Wren"
[board_n16r8]
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; "Finch"
[board_n32r16]
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 32MB

;
; Networks
;
[wifi_home]
wifi_flags =
    -DWIFI_NETWORK_HOME

[wifi_phone]
wifi_flags =
    -DWIFI_NETWORK_PHONE

[wifi_wokwi]
wifi_flags =
    -DWIFI_NETWORK_WOKWI

;
; Ports
;
[modem_port]
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101

[serial_port]
upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110

;
; Programs
;
[noisy_display]	
lib_deps = 
	adafruit/Adafruit NeoPixel
	adafruit/Adafruit SH110X
build_src_filter = 
	+<*>
	-<experiments/>

[web_server]
lib_deps = 
    bblanchon/ArduinoJson	
build_src_filter = 
	-<*>
	+<heartbeat.cpp>
	+<experiments/web_server.cpp>

[esp_test]
build_src_filter = 
	-<*>
	+<experiments/board_test.cpp>

;
; Executables
;
; Wren web server, wifi network
[env:web_server_wren]
extends = 
	esp_base
	; usb_native
	board_n16r8
	web_server
	modem_port
	; wifi_home

build_flags =
	${esp_base.base_flags}
	${wifi_home.wifi_flags}
	${usb_native.usb_flags}

[env:web_server_finch]
extends = 
	esp_base
	board_n32r16
	web_server
	serial_port
	; wifi_home

build_flags =
	${esp_base.base_flags}
	${wifi_home.wifi_flags}

[env:noisy_display]
extends = 
	esp_base
	board_n16r8
	noisy_display
	modem_port
build_flags =
	${esp_base.base_flags}
	${wifi_home.wifi_flags}
	${usb_native.usb_flags}

[env:board_test]
extends = 
	esp_base
	board_n32r16
	esp_test
	serial_port
build_flags =
	${esp_base.base_flags}
	; ${wifi_home.wifi_flags}

[env:native]
build_type = test
platform = native
test_framework = unity
build_flags =
    -std=c++17




; [env:esp32]
; extends = esp_base
; build_src_filter = 
; 	+<*>
; 	-<experiments/>

; [env:wifi-test]
; extends = esp_base
; build_src_filter = 
; 	-<*>
; 	+<heartbeat.cpp>
; 	+<experiments/wifi_events.cpp>

; [env:wifi-scan]
; extends = esp_base
; build_src_filter = 
; 	-<*>
; 	+<experiments/wifi_scanner.cpp>

; ; source files are temporary for ease of use
; [env:wifi_base]
; extends = esp_base
; build_src_filter = 
; 	-<*>
; 	+<heartbeat.cpp>
; 	+<experiments/web_server.cpp>


; [env:wifi-home]
; extends = env:wifi_base
; build_flags =
;     -DWIFI_NETWORK_HOME

; [env:wifi-phone]
; extends = env:wifi_base
; build_flags =
;     -DWIFI_NETWORK_PHONE

; [env:wifi-wokwi]
; extends = env:wifi_base
; build_flags =
;     -DWIFI_NETWORK_WOKWI

; [env:webserver-test]
; extends = env:wifi-home
; ; build_flags =
; ;     -DWIFI_NETWORK_HOME

; [env:webserver-wokwi]
; extends = env:wifi-wokwi
; build_flags =
;     -DWIFI_NETWORK_WOKWI
; ; build_src_filter = 
; ; 	-<*>
; ; 	+<heartbeat.cpp>
; ; 	+<experiments/web_server.cpp>

; ; [env:wifi-wokwi]
; ; build_src_filter = 
; ; 	-<*>
; ; 	+<experiments/neopixel_hysteresis.cpp>
