; PlatformIO Project Configuration File

[platformio]
default_envs = noisy_display
extra_configs =
    platformio-local.ini

[env]
; genuinely universal settings go here

[esp_base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200	
base_flags = 
	-DBOARD_HAS_PSRAM

[usb_native]
usb_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

;
; Boards, named after birds
; Wren — ESP32-S3 N16R8, main NoisyProject board
[board_wren]
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; Swift — ESP32-S3 N32R16, travelling/experiment board
[board_swift]
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 32MB

;
; Networks
;
[wifi_home]
wifi_flags =
    -DWIFI_NETWORK_HOME

[wifi_phone]
wifi_flags =
    -DWIFI_NETWORK_PHONE

[wifi_wokwi]
wifi_flags =
    -DWIFI_NETWORK_WOKWI

;
; Programs
;
[noisy_display]	
lib_deps = 
	adafruit/Adafruit NeoPixel
	adafruit/Adafruit SH110X
build_src_filter = 
	+<*>
	-<experiments/>

[web_server]
lib_deps = 
	adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson	
build_src_filter = 
	-<*>
	+<heartbeat.cpp>
	+<experiments/web_server.cpp>

[esp_test]
build_src_filter = 
	-<*>
	+<experiments/board_test.cpp>


;
; Executables
;
; Wokwi Simulator
[env:wokwi_test]
extends = 
	esp_base
	usb_native
build_src_filter = 
	-<*>
	+<heartbeat.cpp>
	+<experiments/wokwi_test.cpp>
build_flags =
	${esp_base.base_flags}
	${usb_native.usb_flags}

; Wren web server, wifi network
[env:web_server_wren]
extends = 
	esp_base
	; usb_native
	board_wren
	web_server
	modem_port
	; wifi_home

build_flags =
	${esp_base.base_flags}
	${wifi_home.wifi_flags}
	${usb_native.usb_flags}

[env:web_server_swift]
extends = 
	esp_base
	board_swift
	web_server
	serial_port

build_flags =
	${esp_base.base_flags}
	${wifi_home.wifi_flags}

[env:noisy_display]
extends = 
	esp_base
	board_wren
	noisy_display
	modem_port
build_flags =
	${esp_base.base_flags}
	${wifi_home.wifi_flags}
	${usb_native.usb_flags}

[env:board_test]
extends = 
	esp_base
	board_wren
	esp_test
	serial_port
build_flags =
	${esp_base.base_flags}

[env:native]
build_type = test
platform = native
test_framework = unity
build_flags =
    -std=c++17

